SFML = -lsfml-graphics -lsfml-window -lsfml-system

all: step1 step2 step3 step4 step5 step6 step7 step8 step9

step1 : step1.cpp
	clang++ -o step1 step1.cpp $(SFML)

step2 : step2.cpp
	clang++ -o step2 step2.cpp $(SFML)

step3 : step3.cpp
	clang++ -o step3 step3.cpp $(SFML)

step4 : step4.cpp
	clang++ -o step4 step4.cpp $(SFML)

step5 : step5.cpp
	clang++ -o step5 step5.cpp $(SFML)

step6 : step6.cpp
	clang++ -o step6 step6.cpp $(SFML)

step7 : step7.cpp
	clang++ -o step7 step7.cpp $(SFML)

step8 : step8.cpp
	clang++ -o step8 step8.cpp $(SFML)

step9 : step9.cpp
	clang++ -o step9 step9.cpp $(SFML)

clean :
	rm -f step1 step2 step3 step4 step5 step6 step7 step8 step9

